# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.synced_folder "../", "/projs", type: "rsync",
                          rsync__exclude: [
                            ".git/",
                            "node_modules/"
                          ]
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
  end
  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "ansible/playground.yml"
    ansible.limit = "playground"
    ansible.inventory_path = "ansible/inventory"
    ansible.galaxy_role_file = "ansible/requirements.yml"
    ansible.galaxy_roles_path = "ansible/roles"
  end
end
